require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/equipment_kinds", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # EquipmentKind. As you add validations to EquipmentKind, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      name: "Tipo personalizado",
      asset_type_id: AssetType.ups.id,
      generic_fields: {EquipmentKind.generate_field_key => {name: "Marca", type: "string"}},
      specific_fields: {}
    }
  }

  let(:invalid_attributes) {
    {name: nil, generic_fields: {}}
  }

  let(:user) { create(:admin) }

  before do
    sign_in user
  end

  describe "GET /index" do
    it "renders a successful response" do
      EquipmentKind.create! valid_attributes
      get equipment_kinds_url
      expect(response).to be_successful
      expect(response.body).to include("Duplicar")
    end

    it "shows the asset type on each card" do
      asset_type = create(:asset_type, name: "Generador")
      EquipmentKind.create! valid_attributes.merge(name: "Tablero", asset_type_id: asset_type.id)
      get equipment_kinds_url
      expect(response.body).to include("Tablero")
      expect(response.body).to include("Generador")
    end

    it "filters by one or more asset types" do
      generator = create(:asset_type, name: "Generador")
      panel = create(:asset_type, name: "Tablero eléctrico")
      EquipmentKind.create! valid_attributes.merge(name: "Grupo diesel", asset_type_id: generator.id)
      EquipmentKind.create! valid_attributes.merge(name: "Tablero principal", asset_type_id: panel.id)
      EquipmentKind.create! valid_attributes.merge(name: "UPS online")

      get equipment_kinds_url, params: {asset_type_ids: [generator.id]}
      expect(response.body).to include("Grupo diesel")
      expect(response.body).not_to include("Tablero principal")
      expect(response.body).not_to include("UPS online")

      get equipment_kinds_url, params: {asset_type_ids: [generator.id, panel.id]}
      expect(response.body).to include("Grupo diesel")
      expect(response.body).to include("Tablero principal")
      expect(response.body).not_to include("UPS online")
    end

    it "shows an empty message when no equipment kind matches the filter" do
      generator = create(:asset_type, name: "Generador")
      EquipmentKind.create! valid_attributes.merge(name: "UPS online")

      get equipment_kinds_url, params: {asset_type_ids: [generator.id]}

      expect(response.body).to include("No hay tipos de activos para los filtros seleccionados.")
      expect(response.body).not_to include("UPS online")
    end

    context "when user is not admin" do
      let(:user) { create(:user) }

      it "redirects to the root path" do
        get equipment_kinds_url
        expect(flash[:alert]).to eq "No estás autorizado para realizar esta acción."
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      equipment_kind = EquipmentKind.create! valid_attributes
      get equipment_kind_url(equipment_kind)
      expect(response).to be_successful
    end

    context "when user is not admin" do
      let(:user) { create(:user) }

      it "redirects to the root path" do
        equipment_kind = EquipmentKind.create! valid_attributes
        get equipment_kind_url(equipment_kind)
        expect(flash[:alert]).to eq "No estás autorizado para realizar esta acción."
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_equipment_kind_url
      expect(response).to be_successful
    end

    it "renders the asset type dropdown with UPS and the add action" do
      AssetType.ups

      get new_equipment_kind_url
      expect(response.body).to include("Tipo de Activo <abbr title=\"required\">*</abbr>")
      expect(response.body).to include("Seleccioná un tipo")
      expect(response.body).to include("UPS")
      expect(response.body).to include("Añadir nuevo tipo...")
      expect(response.body).to include("Eliminar UPS")
      expect(response.body).to include("Editar UPS")
    end

    context "when user is not admin" do
      let(:user) { create(:user) }

      it "redirects to the root path" do
        get new_equipment_kind_url
        expect(flash[:alert]).to eq "No estás autorizado para realizar esta acción."
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe "GET /duplicate" do
    it "renders a new form prefilled from the source kind" do
      equipment_kind = EquipmentKind.create!(
        valid_attributes.merge(
          name: "UPS de sala",
          description: "Plantilla original",
          specific_fields: {"serie" => {name: "Serie", type: "string"}}
        )
      )
      service_kind = create(:service_kind, name: "Mantenimiento")
      equipment_kind.service_kinds << service_kind

      get duplicate_equipment_kind_url(equipment_kind)

      expect(response).to be_successful
      document = Nokogiri::HTML(response.body)
      expect(document.at_css("#remote_modal_title").text).to eq("Duplicar Tipo de Equipo")
      expect(document.at_css("input[name='equipment_kind[name]']")["value"]).to eq("UPS de sala (copia)")
      expect(document.at_css("textarea[name='equipment_kind[description]']").text.strip).to eq("Plantilla original")
      expect(document.css("input.field-name").map { |input| input["value"] }).to include("Marca", "Serie")
      checkbox = document.at_css("input[name='equipment_kind[service_kind_ids][]'][value='#{service_kind.id}']")
      expect(checkbox["checked"]).to eq("checked")
      form = document.at_css("form#new_equipment_kind")
      expect(form["action"]).to eq(equipment_kinds_path)
      expect(form["method"]).to eq("post")
      expect(form.at_css("input[name='_method']")).to be_nil
    end

    context "when user is not admin" do
      let(:user) { create(:user) }

      it "redirects to the root path" do
        equipment_kind = EquipmentKind.create! valid_attributes
        get duplicate_equipment_kind_url(equipment_kind)
        expect(flash[:alert]).to eq "No estás autorizado para realizar esta acción."
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      equipment_kind = EquipmentKind.create! valid_attributes
      get edit_equipment_kind_url(equipment_kind)
      expect(response).to be_successful
    end

    context "when user is not admin" do
      let(:user) { create(:user) }

      it "redirects to the root path" do
        equipment_kind = EquipmentKind.create! valid_attributes
        get edit_equipment_kind_url(equipment_kind)
        expect(flash[:alert]).to eq "No estás autorizado para realizar esta acción."
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EquipmentKind" do
        expect {
          post equipment_kinds_url, params: {equipment_kind: valid_attributes}
        }.to change(EquipmentKind, :count).by(1)
      end

      it "redirects to the created equipment_kind" do
        post equipment_kinds_url, params: {equipment_kind: valid_attributes}
        expect(response).to redirect_to(equipment_kind_url(EquipmentKind.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EquipmentKind" do
        expect {
          post equipment_kinds_url, params: {equipment_kind: invalid_attributes}
        }.to change(EquipmentKind, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post equipment_kinds_url, params: {equipment_kind: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_content)
      end

      it "re-renders the form via turbo stream when generic_fields are missing" do
        post equipment_kinds_url,
          params: {equipment_kind: {name: "Nuevo tipo", generic_fields: {}}},
          as: :turbo_stream

        expect(response).to have_http_status(:unprocessable_content)
        expect(response.body).to include('turbo-stream action="update" target="remote_modal_body"')
        expect(response.body).to include("debe tener al menos un campo definido")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          name: "Grupo Electrógeno",
          generic_fields: {EquipmentKind.generate_field_key => {name: "Modelo", type: "string"}},
          specific_fields: {"form_link" => {name: "Link al formulario", type: "string"}}
        }
      }

      it "updates the requested equipment_kind" do
        equipment_kind = EquipmentKind.create! valid_attributes
        patch equipment_kind_url(equipment_kind), params: {equipment_kind: new_attributes}
        equipment_kind.reload
        expect(equipment_kind.name).to eq "Grupo Electrógeno"
        expect(equipment_kind.specific_fields["form_link"]["name"]).to eq "Link al formulario"
      end

      it "redirects to the equipment_kind" do
        equipment_kind = EquipmentKind.create! valid_attributes
        patch equipment_kind_url(equipment_kind), params: {equipment_kind: new_attributes}
        equipment_kind.reload
        expect(response).to redirect_to(equipment_kind_url(equipment_kind))
      end

      it "preserves field values when renaming a generic field label" do
        field_key = EquipmentKind.generate_field_key
        equipment_kind = EquipmentKind.create!(
          name: "Tipo personalizado",
          asset_type_id: AssetType.ups.id,
          generic_fields: {field_key => {name: "Marca", type: "string"}},
          specific_fields: {}
        )
        equipment = create(:equipment, equipment_kind: equipment_kind, field_values: {field_key.to_s => "APC"})

        patch equipment_kind_url(equipment_kind), params: {
          equipment_kind: {
            name: equipment_kind.name,
            generic_fields: {field_key => {name: "Fabricante", type: "string"}},
            specific_fields: {}
          }
        }

        expect(equipment.reload.field_values).to eq(field_key.to_s => "APC")
      end

      it "assigns service kinds" do
        equipment_kind = EquipmentKind.create! valid_attributes
        service_kind = create(:service_kind, name: "Inspección especial")

        patch equipment_kind_url(equipment_kind), params: {
          equipment_kind: valid_attributes.merge(service_kind_ids: [service_kind.id])
        }

        expect(equipment_kind.reload.service_kinds).to contain_exactly(service_kind)
      end

      it "clears service kinds when none are selected" do
        equipment_kind = EquipmentKind.create! valid_attributes
        service_kind = create(:service_kind, name: "Inspección especial")
        equipment_kind.service_kinds << service_kind

        patch equipment_kind_url(equipment_kind), params: {
          equipment_kind: valid_attributes.merge(service_kind_ids: [""])
        }

        expect(equipment_kind.reload.service_kinds).to be_empty
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        equipment_kind = EquipmentKind.create! valid_attributes
        patch equipment_kind_url(equipment_kind), params: {equipment_kind: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "soft-deletes the requested equipment_kind" do
      equipment_kind = EquipmentKind.create! valid_attributes
      expect {
        delete equipment_kind_url(equipment_kind)
      }.to change(EquipmentKind.kept, :count).by(-1)
      expect(equipment_kind.reload).to be_discarded
    end


    it "redirects to the equipment_kinds list" do
      equipment_kind = EquipmentKind.create! valid_attributes
      delete equipment_kind_url(equipment_kind)
      expect(response).to redirect_to(equipment_kinds_url)
    end
  end
end
