require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/equipment_kinds", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # EquipmentKind. As you add validations to EquipmentKind, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      name: "Tipo personalizado",
      generic_fields: {EquipmentKind.generate_field_key => {name: "Marca", type: "string"}},
      specific_fields: {}
    }
  }

  let(:invalid_attributes) {
    {name: nil, generic_fields: {}}
  }

  let(:user) { create(:admin) }

  before do
    sign_in user
  end

  describe "GET /index" do
    it "renders a successful response" do
      EquipmentKind.create! valid_attributes
      get equipment_kinds_url
      expect(response).to be_successful
    end

    context "when user is not admin" do
      let(:user) { create(:user) }

      it "redirects to the root path" do
        get equipment_kinds_url
        expect(flash[:alert]).to eq "No estas autorizado para realizar esta acción."
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      equipment_kind = EquipmentKind.create! valid_attributes
      get equipment_kind_url(equipment_kind)
      expect(response).to be_successful
    end

    context "when user is not admin" do
      let(:user) { create(:user) }

      it "redirects to the root path" do
        equipment_kind = EquipmentKind.create! valid_attributes
        get equipment_kind_url(equipment_kind)
        expect(flash[:alert]).to eq "No estas autorizado para realizar esta acción."
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_equipment_kind_url
      expect(response).to be_successful
    end

    context "when user is not admin" do
      let(:user) { create(:user) }

      it "redirects to the root path" do
        get new_equipment_kind_url
        expect(flash[:alert]).to eq "No estas autorizado para realizar esta acción."
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      equipment_kind = EquipmentKind.create! valid_attributes
      get edit_equipment_kind_url(equipment_kind)
      expect(response).to be_successful
    end

    context "when user is not admin" do
      let(:user) { create(:user) }

      it "redirects to the root path" do
        equipment_kind = EquipmentKind.create! valid_attributes
        get edit_equipment_kind_url(equipment_kind)
        expect(flash[:alert]).to eq "No estas autorizado para realizar esta acción."
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EquipmentKind" do
        expect {
          post equipment_kinds_url, params: {equipment_kind: valid_attributes}
        }.to change(EquipmentKind, :count).by(1)
      end

      it "redirects to the created equipment_kind" do
        post equipment_kinds_url, params: {equipment_kind: valid_attributes}
        expect(response).to redirect_to(equipment_kind_url(EquipmentKind.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EquipmentKind" do
        expect {
          post equipment_kinds_url, params: {equipment_kind: invalid_attributes}
        }.to change(EquipmentKind, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post equipment_kinds_url, params: {equipment_kind: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_content)
      end

      it "re-renders the form via turbo stream when generic_fields are missing" do
        post equipment_kinds_url,
          params: {equipment_kind: {name: "Nuevo tipo", generic_fields: {}}},
          as: :turbo_stream

        expect(response).to have_http_status(:unprocessable_content)
        expect(response.body).to include('turbo-stream action="update" target="remote_modal_body"')
        expect(response.body).to include("debe tener al menos un campo definido")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          name: "Grupo Electrógeno",
          generic_fields: {EquipmentKind.generate_field_key => {name: "Modelo", type: "string"}},
          specific_fields: {"form_link" => {name: "Link al formulario", type: "string"}}
        }
      }

      it "updates the requested equipment_kind" do
        equipment_kind = EquipmentKind.create! valid_attributes
        patch equipment_kind_url(equipment_kind), params: {equipment_kind: new_attributes}
        equipment_kind.reload
        expect(equipment_kind.name).to eq "Grupo Electrógeno"
        expect(equipment_kind.specific_fields["form_link"]["name"]).to eq "Link al formulario"
      end

      it "redirects to the equipment_kind" do
        equipment_kind = EquipmentKind.create! valid_attributes
        patch equipment_kind_url(equipment_kind), params: {equipment_kind: new_attributes}
        equipment_kind.reload
        expect(response).to redirect_to(equipment_kind_url(equipment_kind))
      end

      it "preserves field values when renaming a generic field label" do
        field_key = EquipmentKind.generate_field_key
        equipment_kind = EquipmentKind.create!(
          name: "Tipo personalizado",
          generic_fields: {field_key => {name: "Marca", type: "string"}},
          specific_fields: {}
        )
        equipment = create(:equipment, equipment_kind: equipment_kind, field_values: {field_key.to_s => "APC"})

        patch equipment_kind_url(equipment_kind), params: {
          equipment_kind: {
            name: equipment_kind.name,
            generic_fields: {field_key => {name: "Fabricante", type: "string"}},
            specific_fields: {}
          }
        }

        expect(equipment.reload.field_values).to eq(field_key.to_s => "APC")
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        equipment_kind = EquipmentKind.create! valid_attributes
        patch equipment_kind_url(equipment_kind), params: {equipment_kind: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested equipment_kind" do
      equipment_kind = EquipmentKind.create! valid_attributes
      expect {
        delete equipment_kind_url(equipment_kind)
      }.to change(EquipmentKind, :count).by(-1)
    end

    it "redirects to the equipment_kinds list" do
      equipment_kind = EquipmentKind.create! valid_attributes
      delete equipment_kind_url(equipment_kind)
      expect(response).to redirect_to(equipment_kinds_url)
    end
  end
end
